### PR TITLE
feat: add hostedSuppressionsAuthHeader option to provide credentials for the hosted suppression file

### LINKED ISSUE #5783: Download of suppression files with authorization header
**Is your feature request related to a problem? Please describe.**

We are keeping some of our suppression files in our company internal on-premise version control system, and so far have been using simple URLs for referencing and downloading them during the analysis. This is possible as long as the repository allows public access.

For security reasons we would like to disable all public access even to our internal repositories, though. At the moment it is possible to achieve a retrieval of a suppression file even in that case using username and password, but managing a complete user with credentials is cumbersome just for retrieval of a suppression file.

Our version control system offers the creation of access tokens for repositories, which can then be used in an authorization header to access repository content. This allows to create individual tokens per integration, which is also the recommended way.

**Describe the solution you'd like**

It would be nice if the utils for downloading suppression files (and the configuration they use) could support either an 'Authorization: Bearer' header or completely freely configurable extra-headers.

I may be able to implement this and create a pull-request if we can align on the functional solution.

**Describe alternatives you've considered**
- using basic auth with username and password: possible already, but cumbersome in our case
- encoding credentials into the URL somehow: unexpected and somewhat "hacky"

**Additional context**
(none)

### PR DESCRIPTION
**Pull request by ftiercelin**
## Description of Change
add hostedSuppressionsAuthHeader option to provide credentials for the hosted suppression file in the form of the auth header. e.g. 'Basic dXNlcjpwYXNzd29yZA==' or 'Bearer xxxxxxxxxxxxxxxxxxxxxxxx'

## Related issues
- fixes #5783 

## Have test cases been added to cover the new functionality?
yes: see org.owasp.dependencycheck.utils.CredentialHelperTest

### CODE REVIEW

**Comment by ftiercelin** [comment]
Testing with a server requiring either no authentication, a basic or a bearer auth:
``mvn dependency-check:check ``
no access to server, going to default location

``mvn dependency-check:check -DhostedSuppressionsUrl=http://<ip>:8080/bearer/suppressions.xml -DhostedSuppressionsAuthHeader="Bearer THE_TOKEN_PLACEHOLDER"``
server logs:
```
# INFO - HTTP-401 UNAUTHORIZED
# INFO - authorization: 'Bearer THE_TOKEN_PLACEHOLDER'
# INFO - HTTP-200 OK
```
- [x] plugin execution success

``mvn dependency-check:check -DhostedSuppressionsUrl=http://<ip>:8080/unauthenticated/suppressions.xml ``
server logs:
```
# INFO - HTTP-200 OK
```
- [x] plugin execution success

``mvn dependency-check:check -DhostedSuppressionsUrl=http://<ip>:8080/basic/suppressions.xml  -DhostedSuppressionsAuthHeader="Basic dXNlcjpwYXNzd29yZA=="``
server logs:
```
# INFO - HTTP-401 UNAUTHORIZED
# INFO - authorization: 'Basic dXNlcjpwYXNzd29yZA=='
# INFO - HTTP-200 OK
```
- [x] plugin execution success

``mvn dependency-check:check -DhostedSuppressionsUrl=http://<ip>:8080/basic/suppressions.xml  -DhostedSuppressionsAuthHeader="Something else"``
- [x] plugin execution failure ``Invalid configuration for Hosted suppressions: unknown authentication scheme. Supported authentication schemes are Basic and Bearer``

**Comment by aikebah** [comment]
@ftiercelin Looks like our efforts overlapped. I've implemented authentication for the hosted suppressions in the context of #5387 and never spotted #5783 otherwise I would've linked that as well.

Configuration is currently possible only via dependency-check properties file (since the merge of #6949), but addition of user/password configuration options were foreseen for the various integrations in the near future (I had started work on updating (and meanwhile sanitizing) the Ant tasks to add in the missing authentication settings).

Do you see a strong need for adding Bearer authentications in the mix?

Currently a bit short in time, but hope to do a more in-depth review towards the end of the year or very early in the new year. 

Regarding the general approach, I think that (contrary to the suggestion by @jeremylong in ticket #5783) it is better to have explicit configuration for user/password (Basic) or bearer token by separate configuration properties in line with what was already there for the Artifactory Analyzer.

No sense in adding logic to reverse-parse the token in order to supply the appropriate credentials to the apache HTTPClient (#7255 is pending merge which is making authentication pre-emptive to avoid the round-trip of a HTTP 401 for a known-protected server and solve the HTTP-302 based authentication flow that appears to happen in Azure DevOps)

**Comment by ftiercelin** [comment]
@aikebah thanks for the review. no point doing the same job twice. if you are planning to something similar, I have no heartburns about it, let's close this one.
Regarding the token, yes I think tokens should be on the map.

**Comment by ftiercelin** [comment]
no longer required, let's first finish the httpclient5

**Comment by aikebah** [comment]
@ftiercelin exposing and enabling bearer auth (and addition of configurability for the hosted suppressions in the various integrations) only needs the finishing touches of integrating it into the Downloader If you'd like to chime in feel free to take a look at https://github.com/jeremylong/DependencyCheck/tree/feat/hc5-extending-auth, it's a branch that's developed on top of the fix/httpclient5 branch that I hope to finish soon.

**Pull request closed without merging**
