### PR TITLE
Add Data Mirroring in Maven Plugin

### PR DESCRIPTION
**Pull request by hgomez**
Maven Plugin need a way to provides Data Mirroring to Dependency Check core

### CODE REVIEW

**Comment by jeremylong** [comment]
Is the "useDataMirroring" necessary? I would think if the URLs are specified that would indicate we should use the data mirror.  Any objection to me removing the extra flag or do you see a reason to keep it?

**Comment by hgomez** [comment]
Good idea. Please do.

**Comment by jeremylong** [comment]
This was merged by applying a patch and updating the PR prior to committing.

**Comment by jeremylong** [comment]
This has been pushed to 1.1.2-SNAPSHOT

**Pull request closed without merging**
