### PR TITLE
Support NuGet Package References in MSBuild Project Files

### PR DESCRIPTION
**Pull request by paulirwin**
## Description of Change

Adds a new MSBuildProjectAnalyzer for analyzing the new MSBuild format for NuGet package dependency references.

## Have test cases been added to cover the new functionality?

Yes

### CODE REVIEW

**Comment by jeremylong** [comment]
Can one of the admins verify this patch?

**Comment by jeremylong** [comment]
I apologize about how long this PR has been out here. This is going to get merged - I've just been tied up with a ton of other work.

**Comment by paulirwin** [comment]
No worries. Like I mentioned before, when you merge it you might want to make this analyzer experimental for now until we can sort out the transitive dependency problem.

**Comment by jeremylong** [comment]
I apologize that this took me so long to merge. I had (and still do) have every intention of setting up a .NET environment to do more work on analyzing .NET projects - but I just have not had time.

I added this as an experimental analyzer for now.

Thanks for the PR!

**Pull request merged**
