### PR TITLE
Sonatype OSS Index ODC v5 integration

### PR DESCRIPTION
**Pull request by jdillon**
Adjust previous PR to v5 changes and simplify.

Please *squash* when merging.

### CODE REVIEW

**Comment by jdillon** [comment]
Tests are expected to be unhappy until we can release a new client, which will happen very soon. will follow up and confirm once its ready.  PR here is mostly meant for eyes to sanity check at this point.

**Review by ken-duck — APPROVED** [review]
OSSI integration bits LGTM

**Comment by jdillon** [comment]
The "Codacy/PR Quality Review" is complaining about:

```
Avoid unused method parameters such as 'report'.
private Vulnerability transform(final ComponentReport report, final ComponentReportVulnerability source) {
```

And I agree but i'm leaving it asis until I can resolve the VulnerableSoftware for this which may need this information.

**Comment by jdillon** [comment]
Travis CI check seems to not have the deployed 1.2.0 ossindex client bits from central.

**Comment by jdillon** [comment]
Build fails with ... not enough information to know if its related to this change and/or why:

dependencycheck - travis ci 2019-02-26 20-33-02

**Review by jeremylong — APPROVED** [review]
@jdillon thanks! this PR looks great.  The only two things I think we need to fix (and I'll take care of both) are disabling the OSS Index Analyzer on the Maven integration tests like you did with the Ant Task tests and add the configuration options to the site.

**Comment by jeremylong** [comment]
Sorry this has taken me so long to get to - the PR looks great.  Thanks again!

**Comment by jdillon** [comment]
thanks @jeremylong :-)

**Pull request merged**
