### PR TITLE
feat: Remove the need to specify dbDriver for external databases using JDBCv4 ServiceLoader supporting JDBC drivers

### LINKED ISSUE #6937: External database configuration should not require specification of a Database Driver class
**Is your feature request related to a problem? Please describe.**
In order to specify an external non-H2 database it is currently required to specify the dbDriver as the initial configuration already sets it to the H2 driver. 

With JDBC 4.0 (introduced by Java 6) loading the dbDriver explicitly is no longer required, a proper connection-url suffices as long as the dbDriver is on the classpath.

When currently configuring the maven plugin with only an external connectionUrl, user and password the result is an error as the connection-url for postgres is not supported by the H2 driver which still gets activated as the driver to use because of this default configuration.

**Describe the solution you'd like**
We should assume that by now every dbDriver will be compliant with at least the ServiceLoader paradigm introduced by JDBC v4 in the JDBC specification. As JDBC4 does not require explicit driver loading before use it should suffice to specify the connectionString (and user credentials) in order to use an external database other than H2.

In addition to not requiring explicit driver class specification the software should not manually register and deregister the driver (legacy JDBC 3 behavior) by default for JDBC4 database drivers.

The existing explicit driver registration itself should remain an option for users that for some reason cannot put the databasedriver on the classpath (as in that case JDBC 4 ServiceLoader will not be able to auto-discover the driver and explicit loading with a custom classloader would be required) or wants to use an external database for which the drivers are not compliant with the JDBC 4 ServiceLoader mechanism.

Enabling JDBCv4 ServiceLoader based auto-configuration requires the dbDriver to be unset by default and only set when explicitly configured by the user.

**Describe alternatives you've considered**
Leave the configuration as is and always require specification of the driver classname in addition to the connection-url which means DependencyCheck will always use the legacy method of JDBC driver explicit registration.

**Additional context**

Extract from the `mvn verify -Ppostgres -X` output on a trial-project:

```
[DEBUG] Properties updated via merge:

<...>
data.connection_string='jdbc:h2:file:%s;AUTOCOMMIT=ON;CACHE_SIZE=65536;RETENTION_TIME=1000;MAX_COMPACT_TIME=10000;'
<...>
data.user='dcuser'
<...>
data.file_name='odc.mv.db'
<...>
data.driver_name='org.h2.Driver'
<...>
data.password='********'
<...>
analyzer.nugetconf.enabled='true'

[DEBUG] Setting: odc.maven.local.repo='/Users/aikebah/.m2/repository'
[DEBUG] Setting: suppression.file='["filter.xml"]'
[DEBUG] Setting: updater.versioncheck.enabled='true'
[DEBUG] Setting: junit.fail.on.cvss='0.0'
[DEBUG] Setting: analyzer.central.enabled='true'
[DEBUG] Setting: analyzer.artifactory.parallel.analysis='true'
[DEBUG] Setting: data.connection_string='jdbc:postgresql://localhost:5432/dependencycheck'
[DEBUG] Setting: data.user='dcuser'
[DEBUG] Setting: data.password='********'
[DEBUG] Setting: nvd.api.key='********'
<...>
[DEBUG] Scanning fileSet: /Users/aikebah/Projects/DCTrial/src/main/resources
[DEBUG] Scanning fileSet: /Users/aikebah/Projects/DCTrial/src/main/filters
[DEBUG] Scanning fileSet: /Users/aikebah/Projects/DCTrial/src/main/webapp
[DEBUG] Scanning fileSet: /Users/aikebah/Projects/DCTrial
[DEBUG] Loading driver 'org.h2.Driver'
[DEBUG] Loading database connection
[DEBUG] Connection String: jdbc:postgresql://localhost:5432/dependencycheck
[DEBUG] Database User: dcuser
[DEBUG] Database product: postgresql
[DEBUG] DC Schema: 5.5
<...>
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:10.0.3:check (default) on project dctrial: Execution default of goal org.owasp:dependency-check-maven:10.0.3:check failed: Connection factory returned null from createConnection -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.owasp:dependency-check-maven:10.0.3:check (default) on project dctrial: Execution default of goal org.owasp:dependency-check-maven:10.0.3:check failed: Connection factory returned null from createConnection
```

### PR DESCRIPTION
**Pull request by aikebah**
## Description of Change

* Remove the pre-configured dbDriver so that no dbDriver override is required
* Update documentation to more clearly specify that dbDriver specification is only required in specific scenarios
* Issue a warning message when detecting explicit dbDriver configuration for a JDBC driver that is on the classpath

## Have test cases been added to cover the new functionality?

no, a sensible test would require an external database server. Used the local test-project that surfaced the issue for validating the solution working with an external database. Existing test-cases proof that the removal of the dbDriver configuration is not affecting the use of the embedded h2 database (as the H2 driver is also fully supporting the JDBCv4 ServiceLoader mechanism).

### CODE REVIEW

**Comment by jeremylong** [comment]
ack - merge conflicts that will likely take using beyond compare to figure out ;)

**Comment by aikebah** [comment]
@jeremylong I'll work on rebasing it to get rid of them... most likely effect of my editor autoformatting the file on edit

**Comment by aikebah** [comment]
IntelliJ IDEA with ignoring whitespace made the merge-conflict resolution easily.... a typo fix and addition of a missing path were the conflicting changes

**Review by jeremylong — APPROVED** [review]

**Comment by jeremylong** [comment]
Beyond Compare's diff would have been similar - if you ever have to diff a lot of code I always prefer using BC4. It is hands down the best diff tool available.

**Comment by aikebah** [comment]
Up to now I've been quite satisfied with the 3-way merge of IntelliJ IDEA for resolving merge conflicts, but I do know that BeyondCompare is also a strong tool though I've never used it.

**Pull request merged**
