### PR TITLE
Switch to Jackson Blackbird

### PR DESCRIPTION
**Pull request by jeremylong**
Per #2793 switch from afterburner to blackbird.

### CODE REVIEW

**Review by aikebah — APPROVED** [review]

**Comment by jpcmonster** [comment]
just to confirm - with this change, 7.3.0 is no longer JDK8 compatible - or?

**Comment by aikebah** [comment]
It still is, but will give you a warning, see also https://github.com/jeremylong/DependencyCheck/issues/4966

**Comment by jeremylong** [comment]
The warning will be removed with 7.3.1.

**Comment by jpcmonster** [comment]
@aikebah @jeremylong - thanks for the answer.  And thanks again for a great product; even though we have GitHub Enterprise with Dependabot, it doesn't execute Gradle and will not yet report any vulnerabilities for the Gradle package ecosystem.

**Pull request merged**
