### PR TITLE
Fix NspAnalyzer

### PR DESCRIPTION
**Pull request by ktham**
## Root Cause
`NspAnalyzer` fails to parse `package.json` files that contain the following keys:

```javascript

{
  // Should be parsed as a JsonArray but was parsed as JsonObject
  "bundledDependencies": [
    "node-pre-gyp"
  ],

  // Older libraries use license objects rather than JsonString
  {
  "license": {
    "type": "MIT",
    "url": "https://github.com/twbs/bootstrap/blob/master/LICENSE"
  }
}
```

## Changes

* `NspAnalyzer`: parse `"bundleDependencies"` as `JsonArray`
* `NspAnalyzer`: parse `"bundledDependencies"` as `JsonArray`
* `NspAnalyzer`: parse `"license"` as `JsonObject` and subelement `"type"` as `JsonString` in cases where older libraries used a [license object](https://docs.npmjs.com/files/package.json#license)

### CODE REVIEW

**Comment by jeremylong** [comment]
Can one of the admins verify this patch?

**Comment by stevespringett** [comment]
@ktham Thanks for the excellent PR - especially the additional (and much needed) tests. I've verified in my environment the changes. Are these the only changes necessary to fix #835?

**Comment by ktham** [comment]
@stevespringett no problem, I started to use this library and needed this issue fixed 😄  It may not be exhaustive, but those are the only changes that is needed to fix #835 for the set of libraries that was scanned in my project

**Comment by jeremylong** [comment]
@ktham Thank you for the PR! I'm trying to solve one more, non-related, issue and then I plan on pushing a new release (hopefully this weekend).

**Comment by ktham** [comment]
@jeremylong Just wondering if you're close to cutting a release or if there are more things you're trying to squeeze in?

**Comment by jeremylong** [comment]
Recently discovered a threading issue that needs to be dealt with - which is what was causing the delay. We will likely release a version this week and then spend the next dev cycle re-working some code to resolve the threading issues.

**Pull request merged**
