### PR TITLE
CMake Analyzer implementation

### PR DESCRIPTION
**Pull request by dwvisser**
This submission is to partly address #208. The analyzer inspects CMake build files for project name and version information. Sample data is included that gets used by the unit tests.

### CODE REVIEW

**Comment by jeremylong** [comment]
After looking at this a bit I think we need to make a change to some core functionality - specifically the supportsExtension(String) defined in the Analyzer Interface. As the CMakeAnalyzer seems to only care about a specific txt file name. Otherwise this could end up creating dependencies for all txt files that were scanned. My proposal would be to change supportsExtension(String) to supportsFileName(String name, String ext). So we would call this like Analyzer.supportsFileName("something.txt", ".txt");.

Thoughts?

**Comment by jeremylong** [comment]
Because PR #275 was merged, this PR now has merge conflicts.

**Comment by dwvisser** [comment]
Now that #275 is merged, I will be able to use a filename-based filter, and clean this code up some.

**Comment by dwvisser** [comment]
Fixed merge conflicts, and updated to FileFilter mechanism, which nicely simplified the code.

**Comment by jeremylong** [comment]
Dale,

I just realized that this analyzer would be active in Maven, Ant, and Groovy - I could see adding this to the Ant, but probably need to disable by default in the Maven and Groovy plugin? Thoughts?  I'll have to go back and look at the other C analyzers too.

--Jeremy

**Comment by dwvisser** [comment]
Good point. I haven't thought about those users with this (and Autoconf and OpenSSL). I think it's sensible to disable by default in the Maven and Gradle tools.

**Comment by dwvisser** [comment]
Do you want me to add changes that disable this and the other C analyzers in the Maven and Gradle tools?

**Comment by jeremylong** [comment]
If you have time - please, otherwise I will get to it (hopefully) this
weekend).

--Jeremy

**Comment by jeremylong** [comment]
This has been merged

**Pull request closed without merging**
