### PR TITLE
Fix Issue 730 - multiple suppression files

### PR DESCRIPTION
**Pull request by pwhittlesea**
## Description of Change

Add the ability to define multiple suppression files.

##### Maven
```xml
<plugins>
    <plugin>
        <groupId>org.owasp</groupId>
        <artifactId>dependency-check-maven</artifactId>
        <configuration>
            <suppressionFiles>
                <suppressionFile>parent-check-exclude.xml</suppressionFile>
                <suppressionFile>project-check-exclude.xml</suppressionFile>
            </suppressionFiles>
        </configuration>
    </plugin>
</plugins>
```
##### CLI
```sh
dependency-check.sh \
  --project "My App Name" \
  --scan "/java/application/lib" \
  --suppression "parent-check-exclude.xml" "project-check-exclude.xml"
```
##### Ant
```xml
<target name="suppression">
    <dependency-check
            applicationName="test suppression"
            reportOutputDirectory="${project.build.directory}"
            autoupdate="false"
            failBuildOnCVSS="3">
        <suppressionFile>parent-check-exclude.xml</suppressionFile>
        <suppressionFile>project-check-exclude.xml</suppressionFile>
    </dependency-check>
</target>
```

**NOTE**: This change breaks backward compatibility for Ant and Maven users.
Currently Ant users will see the following error on upgrade:
```
Definition of a suppression file via a property has been deprecated. Suppression files are now defined as a nested element, please update your configuration.
```

Upgrade notes have been added to the README.

## Have test cases been added to cover the new functionality?

Additional test cases can be found in:
- **Ant**: `DependencyCheckTaskTest.java`
- **Maven**: `dependency-check-maven/src/it/730-multiple-suppression-files`
- **CLI**: `AppTest.java`
- **Core**: `AbstractSuppressionAnalyzerTest.java`

### CODE REVIEW

**Comment by jeremylong** [comment]
Can one of the admins verify this patch?

**Comment by jeremylong** [comment]
Thanks for the PR!  I'll review and merge it this week and hopefully have a full release next weekend.

**Comment by pwhittlesea** [comment]
Cheers! Ill fix the merge conflicts later today

**Comment by jeremylong** [comment]
After reviewing this my only concern is that it breaks older configurations. If you are using a suppression file you can no longer just upgrade the version number; you must also update the configuration to use the new configuration mechanism.  Before merging I plan on putting the old configuration options back in the code and if used emit a warning about a deprecated configuration option being used, and then add the suppression file from the old configuration option to the list of suppression files.

**Comment by jeremylong** [comment]
Thanks again for the PR! I wish all PRs were as high quality as yours - updating test cases and the documentation. Truly appreciated.

**Comment by pwhittlesea** [comment]
Cheers @jeremylong

**Pull request merged**
