### PR TITLE
org.slf4j.impl.StaticLoggerBinder causes duplicate classes

### PR DESCRIPTION
**Pull request by gertjanal**
Removed org.slf4j.impl.StaticLoggerBinder and added proper dependency

### CODE REVIEW

**Comment by gertjanal** [comment]
Resolves #552

**Comment by gertjanal** [comment]
OK, so the StaticLoggerBinder is not the original StaticLoggerBinder. Why would we need a patched version and why is it in a package of a different party?

**Comment by colezlaw** [comment]
We can't do this. `StaticLoggerBinder` is a class that **we** provide which tells SLF4J which factory to use for logging implementation. This class is necessary to find the binding to the Maven logger so that internal API's which use SLF4J ultimately make their way into the Maven log.

Does the duplicate class warning cause the build to fail? Or is this just a warning from a plugin that looks for duplicate classes? Can that tool be configured to ignore some duplicates?

**Comment by colezlaw** [comment]
And I understand the duplicate now. There's an adapter for Maven so that internal calls to SLF4J make it to the Maven logger, and we provided an Ant adapter so that internal calls to SLF4J make it to the Ant logger. 

The class that this introduces would force all SLF4J calls to go to Log4J, and would end up being a duplicate at runtime (because the CLI uses a different SLF4J implementation).

**Comment by jeremylong** [comment]
Per the discussion in issue #552 - this PR is not being accepted.

**Pull request closed without merging**
