### PR TITLE
Add support for Rubys rbenv

### PR DESCRIPTION
**Pull request by chris-sansone-angi**
## Description of Change
Added support for Rubys rbenv by adding the `bundleAuditWorkingDirectory` command line arg or the `analyzer.bundle.audit.working.directory` setting. This should allow you to do something like the following and have the appropriate version of `bundler-audit` used for your Ruby project:

```
dependency-check -s /path/to/project/repo --format ALL --out /path/to/dependency_check_out --log /path/to/dependency_check_out/dc.log --noupdate --bundleAuditWorkingDirectory /path/to/project/repo
```

### CODE REVIEW

**Comment by jeremylong** [comment]
This will be merged - but I need to consider backward compatibility.  As such, this will not make the 5.1.1 release that will happen within the next 24 hours.

**Comment by chris-sansone-angi** [comment]
Hey @jeremylong - thanks for your review and comment. Can you clarify what part of this PR breaks backwards compatibility? I added a new **_optional_** argument that allows you to specify where the call to the bundler-audit sub-process will be invoked from. If this argument is not specified it will still default to a temp directory during initialization (as specified by `getSettings().getTempDirectory()`) or the directory that the `Gemfile.lock` exists in during the analysis phase which is how it previously worked before my PR.

**Review by jeremylong — APPROVED** [review]

**Comment by jeremylong** [comment]
@csansone-handy What I said was I need to consider backward compatibility (meaning I had not yet done a full review of the PR). Sorry if I was unclear - I did not have time to fully review this as I needed to get the 5.1.1 release out.

Thanks for the PR! This will be included in the next release (which may be as soon as a week).l

**Comment by chris-sansone-angi** [comment]
Awesome thanks for the clarification! Looking forward to the release!

**Pull request merged**
