### PR TITLE
Support nonProxyHosts parameter in settings.xml #444

### PR DESCRIPTION
**Pull request by christiangalsterer**
We tested this a couple of days. Would be great to get this merged soon as we would need a released version for some of our core projects.

Please let me know in case of any question on changes.

### CODE REVIEW

**Comment by christiangalsterer** [comment]
@jeremylong: Do you know when you cut a 1.3.5 release? We are currently depending on a SNAPSHOT build but we need to release some projects where we would need a proper 1.3.5 release. 

Would be great to get a 1.3.5. soon.

**Comment by jeremylong** [comment]
I'm hoping to do relase testing this weekend and publish an updated plugin
shortly.

--Jeremy

**Comment by christiangalsterer** [comment]
Great. Many thanks.

**Comment by christiangalsterer** [comment]
Many thanks for cutting 1.35.

**Pull request merged**
