### PR TITLE
add setting for customize http method when querying timestamp

### PR DESCRIPTION
**Pull request by wmaintw**
Currently, the Downloader will use `HEAD` as HTTP request method to query timestamp, it works most of the time, but it will prevent user from updating if user is behind a strict proxy which only allow `GET` and `POST` method.

So I introduced a setting item:

`downloader.quick.query.timestamp=true`

The default value is `true`, so the Downloader will use `HEAD` in `getLastModified()`, and this is the current behavior, won't affect existing users. The user then could change the value to `false` and in this way, the Downloader will use `GET` as HTTP method to query timestamp.

### CODE REVIEW

**Comment by wmaintw** [comment]
Hi Jeremy, do you have any comments about this change? would you please approve it?

**Comment by jeremylong** [comment]
I plan on merging this - however, there are a lot of other tasks that need to be performed (updating the other interfaces (Maven, CLI, Ant) and updating the related documentation. I should be able to do this soon but I am in the middle of debugging a build issue that only shows up in some linux environments using JDK8.

--Jeremy

**Comment by wmaintw** [comment]
Got it, thank you very much.

**Comment by jeremylong** [comment]
This change has been merged.

**Pull request closed without merging**
