### PR TITLE
feat: add LibmanAnalyzer

### PR DESCRIPTION
**Pull request by ArjenKorevaar**
## Description of Change

Adds an analyzer for Libman package references from libman.json files.

## Have test cases been added to cover the new functionality?

Yes

### CODE REVIEW

**Comment by jeremylong** [comment]
Thanks for the PR! I've been on vacation - I will review this early next week.

**Comment by ArjenKorevaar** [comment]
Rebased onto jeremylong:main

**Review by jeremylong — APPROVED** [review]
LGTM

**Comment by jeremylong** [comment]
Thanks for the PR!

**Pull request merged**
