### PR TITLE
Treeset performance improvements

### PR DESCRIPTION
**Pull request by mfoo**
## Fixes Issue #
https://github.com/jeremylong/DependencyCheck/issues/3454, branched off of the `v6.2.2` tag.

These changes cut just under 20% off of my analysis time.

## Description of Change

Some of the instance variables in the `Dependency` class are already `TreeSet<Identifier>` objects. In a few places we return `Collections.immutableSet(new TreeSet(thingThatIsAlreadyATreeSet))`. The `new TreeSet(...)` call causes the contents of one `TreeSet` to be read into another one at a time, evaluating the `compareTo` method of the `Identifier` subclass to make sure the new `TreeSet` is in order.

The tests all pass locally but I am not certain if this behaviour is intended and that we want to return a copy of the set rather than an immutable wrapper of the set so please examine carefully.

## Have test cases been added to cover the new functionality?

No - open to suggestions, but the current test doesn't enforce that the collection is immutable or that it's a copy so I'm unsure of the intended behaviour.

### CODE REVIEW

**Review by jeremylong — APPROVED** [review]
Thanks for the PR including the general code cleanup - really appreciate it!

**Comment by aikebah** [comment]
@jeremylong (most likely) this merge has caused

```
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[WARNING] An unexpected error occurred during analysis of '/Users/aikebah/.m2/repository/org/springframework/cloud/spring-cloud-kubernetes-fabric8-autoconfig/2.0.0/spring-cloud-kubernetes-fabric8-autoconfig-2.0.0.jar' (Dependency Bundling Analyzer): null
[ERROR] 
java.util.ConcurrentModificationException
    at java.util.TreeMap$KeySpliterator.forEachRemaining (TreeMap.java:2757)
    at java.util.stream.ReferencePipeline$Head.forEach (ReferencePipeline.java:647)
    at org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer.mergeDependencies (DependencyBundlingAnalyzer.java:199)
    at org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer.mergeDependencies (DependencyBundlingAnalyzer.java:180)
    at org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer.evaluateDependencies (DependencyBundlingAnalyzer.java:151)
    at org.owasp.dependencycheck.analyzer.AbstractDependencyComparingAnalyzer.analyzeDependency (AbstractDependencyComparingAnalyzer.java:98)
    at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze (AbstractAnalyzer.java:131)
    at org.owasp.dependencycheck.AnalysisTask.call (AnalysisTask.java:88)
    at org.owasp.dependencycheck.AnalysisTask.call (AnalysisTask.java:37)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
```

**Comment by aikebah** [comment]
Currently running a local full test with only a defensive copy of the treeset for the DependencyBundlingAnalyzer

```
diff --git a/core/src/main/java/org/owasp/dependencycheck/analyzer/DependencyBundlingAnalyzer.java b/core/src/main/java/org/owasp/dependencycheck/analyzer/DependencyBundlingAnalyzer.java
index a4081afab..f0df122a0 100644
--- a/core/src/main/java/org/owasp/dependencycheck/analyzer/DependencyBundlingAnalyzer.java
+++ b/core/src/main/java/org/owasp/dependencycheck/analyzer/DependencyBundlingAnalyzer.java
@@ -23,6 +23,7 @@ import com.vdurmont.semver4j.Semver.SemverType;
 import com.vdurmont.semver4j.SemverException;
 import java.io.File;
 import java.util.Set;
+import java.util.TreeSet;
 import java.util.regex.Matcher;
 import java.util.regex.Pattern;
 import static java.util.stream.Collectors.toSet;
@@ -196,7 +197,8 @@ public class DependencyBundlingAnalyzer extends AbstractDependencyComparingAnaly
             final Dependency relatedDependency, final Set<Dependency> dependenciesToRemove,
             final boolean copyVulnsAndIds) {
         dependency.addRelatedDependency(relatedDependency);
-        relatedDependency.getRelatedDependencies().stream().forEach(d -> {
+        Set<Dependency> orginalRelatedDependencies = new TreeSet<>(relatedDependency.getRelatedDependencies());
+        orginalRelatedDependencies.stream().forEach(d -> {
             dependency.addRelatedDependency(d);
             relatedDependency.removeRelatedDependencies(d);
         });
```

**Comment by aikebah** [comment]
Unfortunately still triggers failures... but maybe only because I'm too modern (Java16)
```
[WARNING] An unexpected error occurred during analysis of '/Users/aikebah/Projects/DependencyCheck/maven/target/local-repo/log4j/log4j/1.2.17/log4j-1.2.17.jar' (Dependency Bundling Analyzer): class org.owasp.dependencycheck.dependency.Dependency cannot be cast to class java.lang.Comparable (org.owasp.dependencycheck.dependency.Dependency is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @f3ef469; java.lang.Comparable is in module java.base of loader 'bootstrap')
[ERROR] 
java.lang.ClassCastException: class org.owasp.dependencycheck.dependency.Dependency cannot be cast to class java.lang.Comparable (org.owasp.dependencycheck.dependency.Dependency is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @f3ef469; java.lang.Comparable is in module java.base of loader 'bootstrap')
    at java.util.TreeMap.compare (TreeMap.java:1563)
    at java.util.TreeMap.addEntryToEmptyMap (TreeMap.java:768)
    at java.util.TreeMap.put (TreeMap.java:777)
    at java.util.TreeMap.put (TreeMap.java:534)
    at java.util.TreeSet.add (TreeSet.java:255)
    at java.util.AbstractCollection.addAll (AbstractCollection.java:336)
    at java.util.TreeSet.addAll (TreeSet.java:310)
    at java.util.TreeSet.<init> (TreeSet.java:160)
    at org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzer.mergeDependencies (DependencyBundlingAnalyzer.java:200)
```
Fixing my Java to 8 and retrying

**Comment by aikebah** [comment]
Realized that TreeSet is not required for the defensive copy, so changed it to a simple ArrayList - we just need some copy of the set's elements to stream over

```
 core/src/main/java/org/owasp/dependencycheck/analyzer/DependencyBundlingAnalyzer.java 
index a4081afab,a4081afab..be2e61a9c
@@@ -22,7 -22,7 +22,9 @@@ import com.vdurmont.semver4j.Semver
  import com.vdurmont.semver4j.Semver.SemverType;
  import com.vdurmont.semver4j.SemverException;
  import java.io.File;
++import java.util.ArrayList;
  import java.util.Set;
  import java.util.regex.Matcher;
  import java.util.regex.Pattern;
  import static java.util.stream.Collectors.toSet;
@@@ -196,7 -196,7 +198,8 @@@ public class DependencyBundlingAnalyze
              final Dependency relatedDependency, final Set<Dependency> dependenciesToRemove,
              final boolean copyVulnsAndIds) {
          dependency.addRelatedDependency(relatedDependency);
--        relatedDependency.getRelatedDependencies().stream().forEach(d -> {
++        ArrayList<Dependency> orginalRelatedDependencies = new ArrayList<>(relatedDependency.getRelatedDependencies());
++        orginalRelatedDependencies.stream().forEach(d -> {
              dependency.addRelatedDependency(d);
              relatedDependency.removeRelatedDependencies(d);
          });
```
Made my local builds pass

Unsure how much of the performance gains are kept for large repositories with this defensive copy in place

**Comment by aikebah** [comment]
@jeremylong There are more places where TreeSet gets concurrently modified while iterating over it. Got one in org.owasp.dependencycheck.analyzer.FalsePositiveAnalyzer.removeBadMatches(FalsePositiveAnalyzer.java:281) when generating a report for an FP issue. Are you already looking in to them? Or shall I open an issue and work on it?

**Comment by jeremylong** [comment]
@aikebah I am fixing this one right now (slightly different then your suggestion) - but haven't looked for other locations yet. If you have time to identify the other locations that would be great.

In this case - rather then copy the TreeSet I just added a `clearRelatedDependencies()` to avoid clearing the entries one by one.

```java
        relatedDependency.getRelatedDependencies().stream()
                .forEach(dependency::addRelatedDependency);
        relatedDependency.clearRelatedDependencies();
```

**Comment by aikebah** [comment]
@jeremylong Your solution was one that I was pondering about as well, but needed more time to see if that would fit well into the scheme things.
For now besides the dependencyBundlingAnalyzer I suspect (but haven't proven) that DependencyMergingAnalyzer will suffer from the same at lines [147-149](https://github.com/jeremylong/DependencyCheck/blob/6832c6434cf60df146f0ff6704c4c082cee13519/core/src/main/java/org/owasp/dependencycheck/analyzer/DependencyMergingAnalyzer.java#L147-L149).

And as mentioned in my DC-reports I see concurrentmodification issues in [FalsePostiveAnalyzer.removeBadMatches](https://github.com/jeremylong/DependencyCheck/blob/6832c6434cf60df146f0ff6704c4c082cee13519/core/src/main/java/org/owasp/dependencycheck/analyzer/FalsePositiveAnalyzer.java#L281) while iterating over the VulnerableSoftwareIdentifiers and removing them when there's a suppression match

**Pull request merged**
