### PR TITLE
Implement configuration item "quickQueryTimpstamp" in grade plugin

### PR DESCRIPTION
**Pull request by wmaintw**
Hi Jeremy,

Previously I added a new Settings item `downloader.quick.query.timestamp` in Core module, and I'v implemented it in gradle plugin, and fixed some publish issues as well, would you please review the changes?

Best Regards.

### CODE REVIEW

**Comment by jeremylong** [comment]
Wei,

I can't merge this pull request as it will re-introduce the bloat into the repo that I recently removed:

```
wmaintw wants to merge 3,252 commits into jeremylong:master from wmaintw:master
```

I had sent messages out to people about this (see [archived post](https://groups.google.com/forum/#!searchin/dependency-check/bfg/dependency-check/DFByzWtubDE/4LP9UZUfBz4J)). This should not happen again in the future - but we did need to cleanup the size of the repo; sorry for any inconvenience.

The easiest way to fix this might be to re-clone to a new directory, copy the groovy files from the old repo into the new one and then delete the old repo.

--Jeremy

**Comment by wmaintw** [comment]
Sorry for the inconvenience, I will delete the old one and re-fork the repo, and then submit new pull request.

**Comment by wmaintw** [comment]
Hi Jeremy,

I've created a new pull request (https://github.com/jeremylong/DependencyCheck/pull/305), please close this one.

Best Regards.

Wei MA

**Comment by wmaintw** [comment]
Just noticed that, I can close the pull request :)

**Pull request closed without merging**
