### PR TITLE
Adding version to the composer.lock displayFileName

### PR DESCRIPTION
**Pull request by brianf**
## Description of Change
Added the version to the displayFileName
Added basic test for composer parsing, including the new version
Changed output to debug

## Have test cases been added to cover the new functionality?

*yes*

### CODE REVIEW

**Comment by jeremylong** [comment]
Can one of the admins verify this patch?

**Review by jeremylong — APPROVED** [review]

**Comment by brianf** [comment]
About the most recent changes... in subsequent testing I discovered that there was almost always an extra, empty dependency left around for the composer.lock file. Since this never gets evidence added to it, it was pointless to leave in the report. I made sure this only gets removed when there are dependencies added from parsing the lock file, so nothing is accidentally removed.

**Comment by brianf** [comment]
The build simply ran past the allocated 15 minutes?

**Comment by brianf** [comment]
After looking at some of the other analyzers, I'm going to take a standardized approach. Pulling this pull for now.

**Pull request closed without merging**
