### PR TITLE
Added Batch insert for References and Vulnerabilities

### PR DESCRIPTION
**Pull request by alefq**
Applies batch inserts for reference and vulnerability tables,
solves the slow one-by-one insert process, for Vulnerabilities
with several references/vulnerabilities associated.

## Description of Change

Makes use of batch capabilities of PreparedStatement. Executes updates every 1000 ( MAX_BATCH_SIZE), slowing down time for vulnerabilities updates by a near 10x factor on external databases (Postgresql for instance). 
Tested on H2 (default), and Postgresql. 

## Have test cases been added to cover the new functionality?
no

Tests available already cover the process. All tests where executed before pushing code to forked repository.

### CODE REVIEW

**Comment by jeremylong** [comment]
Can one of the admins verify this patch?

**Comment by jeremylong** [comment]
We previously had batching enabled and under MySQL ran into issue https://github.com/jeremylong/DependencyCheck/issues/503.

While other changes have been made to the `Vulnerability` and `VulnerableSoftware` objects - adding the batching support back in will require additional testing on MySQL (and my require additional updates to the `equals()` and `compareTo()` methods of `VulnerableSoftware` (see issue #928).

**Comment by alefq** [comment]
Is there regression tests for those issues?
Sounds more like a Mysql jdbc driver problem rather a Dependency Check issue.
I can look a little deeper into the issue with some more information.
Is there a branch or tag with previous version you are mentioning?
I made the patch, and will keep it in my fork, because making millions of inserts, one by one (in nested loops), is really slow and unefficent for my postgresql setup.

**Comment by jeremylong** [comment]
Unfortunately, no. I don't maintain a full suite of tests against each database. However, if we make batch support configurable I suppose anyone that runs into the issue they can disable batch support.  Look at the history of the CveDB  and you'll see that this was halfway implemented (i.e. it had a boolean option - but I do not believe I ever exposed it - and finally just removed it).

**Comment by alefq** [comment]
I will add a flag to disable batch inserts, then create a new Pull Request.

**Pull request closed without merging**
