### PR TITLE
Use Directoryscanner from the ant package

### PR DESCRIPTION
**Pull request by hansjoachim**
As discussed briefly in #153, this replaces the copy'n'pasted DirectoryScanner and related classes with the one from the ant jar. I didn't get a reply on some of the follow-up questions, so I figured I might present my experiment here and we might discuss it.

This replaces nearly 10.000 lines with less than 10 and seems to work just as fine. It does introduce a dependency for this module (ant is already used elsewhere in the project), so there might be arguments for keeping it the way it is.

### CODE REVIEW

**Comment by awhitford** [comment]
Funny, I was looking at this too.  I basically did the same thing -- EXCEPT that I also leveraged the [maven-shade-plugin](https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html#minimizeJar) to merge a subset of the `ant` dependency (to satisfy the concern of including the `ant` dependency -- which honestly shouldn't be a big concern if you ask me).

See my PR #354.  Personally I prefer yours since I am not concerned about including an Ant dependency.  But if that does bother you, the Shade plugin can help.

**Comment by hansjoachim** [comment]
Cool :) 

I guess it is up to the maintainer to review whether this should be merged and in that case which approach.

Btw, do you have any suggestions for resources or small examples to look at for the shade plugin? I've read a bit about it, but I don't think I fully grasped it yet. I would especially like how to properly compare before and after to see how it affects the artifacts.

**Comment by jeremylong** [comment]
Thanks! I went back and forth over just included ant as a dependency vs. what I had done. I agree this is cleaner.

**Comment by awhitford** [comment]
The Shade Plugin can basically merge jar files into your jar.  This is often used to avoid packing around a third party jar, or perhaps even embedding a particular version to avoid some kind of conflict.  (It can rename the embedded jar too -- so `org.apache.ant` could be renamed `org.owasp.ant`, for example -- now it can coexist with `org.apache.ant`.)

Besides the [plugin documentation](http://maven.apache.org/plugins/maven-shade-plugin/), personally I inspect the resulting jar to understand if the configuration is doing what I want.  You can use the `jar` command like:
  `jar tf target/dependency-check-1.3.1-SNAPSHOT.jar`

Or since a `jar` is also really a `zip` file, you can use an archive utility like 7-Zip to inspect.

_Hope this helps!_

**Pull request merged**
