### PR TITLE
Improve Node.js and NSP analyzers

### PR DESCRIPTION
**Pull request by jeremylong**
## Fixes Issue #993 and #991 

Removed the retired annotation from the Node Package Manager analyzer and updated it so that instead of reading package.json - it analyzes the package-lock.json or shrinkwrap.json. Only the package-lock.json or shrinkwrap.json from the root directory will be analyzed; if there are package-lock.json contained in the dependencies within the node_modules directory they will not be analyzed. 

Disabled the CPE Analyzer for Node dependencies; this is due to the incredibly high false positive rate. If one did want to re-enable the CPE Analyzer for Node dependencies simply remove "npm" from the setting `ecosystem.skip.cpeanalyzer`. This setting/environment variable is a comma seperated list of eco systems for which the CPE analyzer will be skipped. Currently, only "npm" is in the list but more may be added in the future.

Update the dependency-check.json report format. Specifically, the identifiers section was updated to better support Node. In addition, some minor changes were made to the HTML and CSV report formats.

## Have test cases been added to cover the new functionality?

Test cases were updated.

### CODE REVIEW

**Comment by jeremylong** [comment]
Can one of the admins verify this patch?

**Comment by stevespringett** [comment]
I'm taking a look. Will provide feedback Monday or Tuesday.

**Review by stevespringett — COMMENTED** [review]
Upon initial review and execution, I noticed that the HTML and XML reports only contain vulnerable dependencies. Dependencies without vulnerabilities are not listed.

SHA1 and MD5 hashes should not be included in the report. The isVirtual should be set to true and the hashes should be null or empty.

On a typical node project that has multiple versions of the same dependency (such as jquery), you'll end up with the filename = ...package.json?jquery multiple times. What affect will this have? Will it only list jquery once? If so, that is not the behavior we want. We actually want jquery (in this case) being listed multiple times.

I have some more testing to do, but it's looking good so far. Will provide additional feedback Monday or Tuesday

**Comment by jeremylong** [comment]
@stevespringett regarding "Dependencies without vulnerabilities are not listed." - do you have a shrinkwrap.json or package-lock.json? Those are analyzed by the Node Package Analyzer to obtain the list of dependent libraries used by the node application. Then the package.json is used by the NSP Analyzer to identify vulnerable dependencies.

If the package-lock.json only has multiple versions of the library then it will be listed multiple times. Depending on how things are setup they multiple versions of the same library will either result in "related dependencies" and/or additional entries in the "Referenced In Project/Scope:" section.

**Comment by stevespringett** [comment]
In my experience, shrinkwrap json is typically only used when creating and publishing node modules. Modules that are published to the npm repo that include shrinkwrap.json will be guaranteed to include the specified version of each of the dependencies specified in the file.

When developing applications however, shrinkwrap json is rarely used. Applications are not published to the npm repo. I just checked, and none of the node apps that I've ever worked on have a shrinkwrap json. You can refer to https://github.com/OWASP/NodeGoat for an example of a Node application that doesn't have shrinkwrap.

In the case of NodeGoat, `npm ls` will result in a tree containing 1191 packages, whereas Dependency-Check only includes 4.

If `npm install` is run prior to Dependency-Check, Dependency-Check will collect evidence from node_modules and return a report consisting of 981 dependencies (706 unique).

**Comment by jeremylong** [comment]
Regarding the npm-shrinkwrap.json vs the package-lock.json - the reason npm-shrinkwrap.json is being included is due to the [package-lock.json documentation](https://docs.npmjs.com/files/package-lock.json) that states:

> If both package-lock.json and npm-shrinkwrap.json are present in the root of a package, package-lock.json will be completely ignored.

Regarding the differences in the counts between `npm ls` and dependency-check if you look you will see a ton of duplicates listed in `npm ls`. On NodeGoat try running:

```bash
npm install
npm ls | sed 's/^[ └│┬├─└]*//' | sed 's/ deduped//' | grep -v ^$ | grep -v "owasp-nodejs-goat" | sort -fu | wc -l
```

You will get 860 unique dependencies. Previously you would have gotten the incorrect count from dependency-check as there was an error in parsing due to multiple licenses for some dependencies; I have just updated the PR so that when you run:

```bash
./dependency-check.sh -s /Users/someone/projects/samples/NodeGoat -l out.txt -o . --disableAssembly --project node
```

You will get 860 unique dependencies. We have to disable the Assembly Analyzer as one of the node.js dependencies contains an `exe`.

**Comment by ammy1999** [comment]
hello, I add a stage dependencuCheck in jenkins file, as result : I have a lot of vulnerabilities and a html report , the problem now, I want add a suppress file for the false positive but when I click in suppress button, it doesn't work , So what can I do please !!

**Comment by stevespringett** [comment]
try viewing the report outside of Jenkins - Jenkins has a built in CSP that prohibits the execution of inline javascript. Copy the file locally, and open it there.

**Pull request merged**
