### PR TITLE
don't stop SuppressionAnalyzer if one suppression file can't be load

### PR DESCRIPTION
**Pull request by stboissdev**
## Fixes Issue #
When you have multiple suppression files and a file can not be loaded, the following files will never be analyzed.

## Description of Change

when a file can't be load, no SuppressionParseException was throw , but a warning was logged with suppressionFilePath 

## Have test cases been added to cover the new functionality?

*yes*

### CODE REVIEW

**Comment by jeremylong** [comment]
Can one of the admins verify this patch?

**Comment by jeremylong** [comment]
@stboiss I've been considering this PR for a while now and I don't think it should be merged. Specifically, if a suppression file cannot be read that means the configuration is wrong and the build/execution should fail.  If you don't want the build to fail because the dependency-check-maven plugin (or gradle, ant, etc.) then you can configure them with `failOnError=false`.  Would that work?

**Comment by stboissdev** [comment]
@jeremylong even with this option, if one file can not be loaded, the following files will not be loaded.

**Comment by jeremylong** [comment]
Changes were made in master that will allow other suppression files to be loaded even though one of the files was invalid. Does that combined with `failOnError=false` satisfy your issue?

**Comment by stboissdev** [comment]
OK rules are loaded but the analysisTask wil not execute. it would be necessary to differentiate fatal or non-fatal InitializationException.

**Comment by jeremylong** [comment]
The concept of a fatal initialization exception has been added and will be included in the next release.

**Comment by jeremylong** [comment]
This update was included in the 3.0.0 release.

**Pull request closed without merging**
