### PR TITLE
Thread Safety Updates

### PR DESCRIPTION
**Pull request by jeremylong**
## Fixes Issues
#860, #843, #833, #802, #690

## Description of Change

In Jenkins and other build systems - parallel builds were causing failures. This PR has refactored a lot of code to correct the threading issues. More detailed discussion of the changes can be found below:

The `Engine` object was updated so that when the list of dependencies is retrieved - it is an unmodifiable array of dependencies. If dependencies need to be added or removed methods exist on the Engine object itself to perform these functions.

`Settings` and `CveDB` singletons were refactored - analyzers can obtain references to these via the `Engine` object. 

An additional initialization step was added to the `Analyzer` interface. When an analyzer is instantiated by the engine the calls will be done in this order: `initialize(settings)`, `prepare(engine)`, `analyze(dependency, engine)`, and finally `close()`.

`EvidenceCollection` was completely refactored and for all intensive purposes any custom analyzers that previously used this object (obtained via the `Dependency` object for vendor, product, and version collections) must be updated to utilize the dependency object itself to update evidence. Example:

```java
/* old */
dependency.getVendorEvidence().addEvidence(evidence);
/* new */
dependency.addEvidence(EvidenceType.VENDOR, evidence);
```

The `Dependency` object is now thread safe. As such, any lists used (e.g. evidence, identifiers) are
unmodifiable copies of the internal list. Any modifications must be done via the dependency object itself (e.g. `dependency.removeIdentifier(i)`).

## Have test cases been added to cover the new functionality?

Tests were updated appropriately.

### CODE REVIEW

**Comment by jeremylong** [comment]
Can one of the admins verify this patch?

**Comment by stevespringett** [comment]
Fantastic job!!!

I noticed that the Travis build seems to always fail on Java7 - does the same on some of my projects. Know the issue?

Have 3.0.0-SNAPSHOT's been pushed yet, and if not, when do you think that will happen?

**Comment by jeremylong** [comment]
@stevespringett regarding travis-ci - I believe their trusty image for java 7 no longer supports oraclejdk7; you have to change your .travis.yml to use openjdk7.

Regarding merging this PR into master - that will likely happen soon (which will cause the 3.0.0-snapshots to be pushed to artifactory). I'm doing some more local testing with mono and ruby to validate that I haven't broken anything ;)  I actually may merge this in a few hours... Tomorrow morning at the latest - unless I find a bug.

**Comment by jeremylong** [comment]
While other bugs may cause the build to randomly fail (see #897 and there might be an issue in the Ant Tasks unrelated to #897 or it is the exact same issue) - this PR is considered complete and will be merged.

**Pull request merged**
