### PR TITLE
Fix aggregate scan set

### PR DESCRIPTION
**Pull request by jeremylong**
## Fixes Issue #1421 

The ScanSet implementation for the Maven plugin did not work for aggregate goals. This PR enables the standard Maven layout to be scanned (or alternatively one configured in the build).

## Have test cases been added to cover the new functionality?

Yes

### CODE REVIEW

**Comment by jeremylong** [comment]
Can one of the admins verify this patch?

**Comment by jeremylong** [comment]
@stevespringett Could you take a look at this PR - specifically the bit of code that sets up the scan set: https://github.com/jeremylong/DependencyCheck/pull/1422/files#diff-34442e326d7be233d2d63917a6ee0ff6R1010

For the aggregate goal to work - I changed from using the scanSet field to a local variable and if it is an aggregate build with a ScanSet defined we now perform a deep copy and adjust the directory if it is not absolute to point to the child module.  Looks right in testing - but I would still like another set of eyes.

**Comment by stevespringett** [comment]
@jeremylong I don't see anything that pops up as being incorrect. It appears the existing 'check' goal will continue to work as expected and the 'aggregate' goal should do what we think.

The only thing that caught my eye was:

`FileSet[] projectScan = scanSet;`

I was expecting .clone() here, but I went through the code and it doesn't appear there would be any anomalies from doing it the way its currently written.

**Comment by jeremylong** [comment]
@stevespringett thanks - actually that assignment statement you pointed out should not have been there; it was never used and was just residual from an earlier, incorrect implementation.

**Comment by jeremylong** [comment]
@stevespringett also - clone was not used as `FileSet` does not support clone and a clone of an array of objects only create a new array with references to the object. That doesn't work as I need to leave the original objects intact.

**Pull request merged**
