### PR TITLE
make Error on personal Suppression File to not fatal

### PR DESCRIPTION
**Pull request by stboissdev**
## Fixes Issue #

if one personal suppression file fails to load, analyzer stops after prepare step and base suppression File Rules are not processed

## Description of Change
I change to make not fatal Error, if personal suppression file fails to load

## Have test cases been added to cover the new functionality?
?

### CODE REVIEW

**Comment by jeremylong** [comment]
Can one of the admins verify this patch?

**Comment by jeremylong** [comment]
thanks!

**Comment by stboissdev** [comment]
@jeremylong, when do you plan to make the next release?

**Comment by jeremylong** [comment]
My plan is next weekend. I want to go through the FP and likely add the ability to suppress NSP findings.

**Pull request merged**
