### PR TITLE
Add Shutdown Hook to remove h2 lock file

### PR DESCRIPTION
**Pull request by jeremylong**
## Fixes Issue #1000 & #1027 

Updated console output if a lock file exists and added a shutdown hook to ensure that the custom h2 db lock file gets removed when the JVM exits.

### CODE REVIEW

**Comment by jeremylong** [comment]
Can one of the admins verify this patch?

**Comment by stefanneuhaus** [comment]
Is this also expected to work with the Gradle Daemon? I'm not 100% sure if the current approach will work when the Gradle daemon process survives the build.

**Comment by jeremylong** [comment]
@stefanneuhaus I've tested the shutdown hook with gradle and it appears to work as expected (i.e. it gracefully shutdowns and removes the lock file).

**Comment by stefanneuhaus** [comment]
@jeremylong I just also tested the shutdown hook. When not using the Gradle daemon the shutdown hook works as expected. But when using the daemon I am left with a lock file:

1. Remove H2 DB (in "~/.gradle/caches/dependency-check-data/3.0/") 
2. ./gradlew --daemon dCAn ("--daemon" is the default since quite some time)
3. Once the H2 update is in progress press CTRL+C
4. Observe that "dc.update.lock" exists

Run "jps" to get the PID of the "GradleDaemon" process and kill it. Observe that the lock file gets properly deleted.

Running builds with the Maven plugin or CLI client in this state should be no problem in most cases, as the Gradle build stores the DB in a different location per default.

Each time I started a new build my old daemon could not be reused and has been stopped prior to starting a fresh one (for whatever reason; I did not dig into this), thereby triggering the shutdown hook again. But of course this is not the default behavior. In fact there can be even multiple instances of the daemon running, each having different configurations.

Though I did not manage to run into issues, I would expect that this is at least possible. Nevertheless even if this solution is not 100% bullet proof, it is at least a big step forward and prevents issues in most cases.

**Pull request merged**
