### PR TITLE
docs: Clarify OSS index credentials

### LINKED ISSUE #4533: Add ability to use OSS Index APIKey instead of username/password
When using keys in a continuous build system it is always preferable to use a key as opposed to a username/password, as if the key is compromised, it doesn't lead to the username being leaked, as well an any password re-use that might happen.

**Describe the solution you'd like**
Add a `--ossIndexApiKey` that allows the usage of the ApiKey instead of username/password.

**Describe alternatives you've considered**
We can use username/password.

**Additional context**
General security guidelines prefer to use a key instead of the username/password.

### PR DESCRIPTION
**Pull request by marcelstoer**
This is what I propose for the CLI documentation. Once you're happy with the text, I'll amend this PR with fixes for the Gradle and Maven docs.

Fixes #4533.

### CODE REVIEW

**Comment by aikebah** [comment]
Looks good to me

**Comment by marcelstoer** [comment]
> I'll amend this PR with fixes for the Gradle and Maven docs

Done

**Comment by marcelstoer** [comment]
Sorry, the bloody editor mangled the whitespace. Need to redo this.

**Comment by aikebah** [comment]
> Sorry, the bloody editor mangled the whitespace. Need to redo this.

Yeah... know the feeling.... these modern smart IDEs that know Markdown and auto-format tables on edit... been there, done that several times

**Comment by marcelstoer** [comment]
Ready

**Review by jeremylong — APPROVED** [review]
LGTM

**Pull request merged**
