### PR TITLE
Detect ecosystems using AhoCorasickDoubleArrayTrie

### PR DESCRIPTION
**Pull request by skjolber**
## Partly fixes Issue #2255 
Combined performance and functional change.

## Description of Change
Detecting on ecosystems is done partly via searching the issue textual description for hints. This PR replaces a `String.indexOf(..)` approach with use of [AhoCorasickDoubleArrayTrie](https://github.com/hankcs/AhoCorasickDoubleArrayTrie). Search hits are now used to score the ecosystems (a simple count) for cases where a single issue could belong to multiple ecosystems. In addition, filtering is somewhat more advanced.

## Have test cases been added to cover the new functionality?
Yes. But some discussion is still needed:

 * add more / better keyword search? Perhaps even product searches, i.e. like from apache.
 * are unit test examples acceptable (in .txt files)?

The AhoCorasickDoubleArrayTrie project does not get top score on its code patterns in my book, but seems to do the job at an acceptable level.

## Results
Code for performance-testing and diff has been added to the [ecosystem](https://github.com/skjolber/datasets-json-benchmark/tree/ecosystem) branch in a seperate project.

 * single-thread performance: from about 8 seconds to 0.5 seconds. Effective improvement depends on the number of cores. 
 * diff attached in zip file.

### CODE REVIEW

**Comment by skjolber** [comment]
[ecosystem.zip](https://github.com/jeremylong/DependencyCheck/files/4340892/ecosystem.zip)

Summary:
Composer added 13
Composer removed 51
Composer kept 18545
Java added 776
Java removed 37
Java kept 784
python added 0
python removed 2
python kept 412
null added 69
null removed 849
null kept 71152
CMAKE added 46
CMAKE removed 9
CMAKE kept 14526
npm added 57
npm removed 0
npm kept 142
perl added 1
perl removed 9
perl kept 269
ruby added 0
ruby removed 5
ruby kept 190

**Comment by jeremylong** [comment]
This might take a bit of research as I'm comparing the differences between the old algorithm and the new.  So this is going to get merged - but may not make the next release.

**Comment by skjolber** [comment]
I guess the database must be flushed when this change is released, at least I have not added any  migration support. 

Another discussion point: What is the ideal order when score are tied? Or would it make sense to map a single cve to multiple ecosystems?

**Comment by jeremylong** [comment]
This is not going to make the 5.3.2 release. In reviewing this I've found other areas that need to be cleaned up with regard to the ecosystem mechanism. Current working branch is https://github.com/jeremylong/DependencyCheck/tree/updateEcosystemLogic - which includes this PR.

**Comment by skjolber** [comment]
@jeremylong sounds good, lets move the discussion to the new PR when ready.

**Comment by jeremylong** [comment]
I finally finished the updates for this PR. A new PR was submitted: #2610.

**Pull request closed without merging**
