### PR TITLE
Support jenv

### PR DESCRIPTION
**Pull request by binkley**
## Description of Change

This is minimal support for [`jenv`](http://jenv.be), a widely used environment tool on MacOS (Linux/WSL also, but less so) to setup the Java environment for particular versions.  In the case of DependencyCheck, it requires Java 8 (1.8).

### To enable

If `jenv` is not installed, this is irrelevant.

If `jenv` is installed, add a JDK version 8 (ie, `jenv add /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64` on Linux/WSL for Ubuntu/Debian-like; similar with a different path on MacOS.)

This PR sets up a **local** configuration using JDK 8 (meaning, only in effect when in the DependencyCheck project directories).

**&#9758;** You may still need to set up the `JAVA_HOME` environment variable (YMMV, it is unclear why; example for Linux):

```
$ export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64
```

## Have test cases been added to cover the new functionality?

N/A.  If the user has the wrong Java version, the build goes awry, including any number of problems:
- Wrong class file version
- API changes
- Reflection failiing

### CODE REVIEW

**Comment by mprins** [comment]
this overlaps with #2569 but there is no relation between jenv and maven wrapper

**Comment by binkley** [comment]
@mprins Hmmm.  I thought the Maven wrapper PR was merged to master?  I'll recreate a fresh branch off `master`, and drop in the jenv file.  Thanks for spotting this!

**Comment by jeremylong** [comment]
Add `.java-version` via 4bf52a2.  We won't merge this PR as it contains the mvn wrapper.

**Comment by binkley** [comment]
@mprins What mistake am I making?  I'm seeing this branch having just the one file:
```
~/src/DependencyCheck$ git br
  master
* support-jenv

~/src/DependencyCheck$ git diff master
diff --git a/.java-version b/.java-version
new file mode 100644
index 000000000..625934097
--- /dev/null
+++ b/.java-version
@@ -0,0 +1 @@
+1.8

~/src/DependencyCheck$ git co master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

~/src/DependencyCheck$ git pull
Current branch master is up to date.
```

**Comment by jeremylong** [comment]
You might have merged  #2569
<https://github.com/jeremylong/DependencyCheck/pull/2569> into your master.
Thus, when you created this PR it included the wrapper commit.

--Jeremy

**Comment by binkley** [comment]
@jeremylong Thank you for setting things right.  I did more checking and confirmed.

Reminder for future self: `master` on forks work like branches on origin.

**Pull request closed without merging**
