### PR TITLE
Issue #280 - Gradle: No such property outputDirectory

### PR DESCRIPTION
**Pull request by willis7**
This changeset includes a fundamental change to the way this plugin operates. The extension now allows for lazy loading of the task properties, which are normally evaluated during the configuration phase. This allows for easier extension of the plugin at a later date.

As part of this changeset I have also included some unit tests. The test specifications describe the usage of this plugin.

Unfortunately, the original author of this plugin was also the publisher and so he will need to publish this new version.

### CODE REVIEW

**Comment by jeremylong** [comment]
FYI - I am planning on merging this. However, I am trying to debug a problem so it might be another week before I complete the merge.

**Comment by willis7** [comment]
No problem. I have connected with the original author and asked for a peer review too. Hopefully he will also publish the new version.

**Comment by wmaintw** [comment]
I've reviewed the changes, it looks good for me.

**Comment by willis7** [comment]
Hi @wmaintw, when this has been merged would you be kind and publish with the Gradle plugins portal?

**Comment by wmaintw** [comment]
Sure, will do that once this merge request been approved.

By the way, beside Gradle plugins portal, I will publish this plugin to Maven central as well.

**Comment by jeremylong** [comment]
Wei,

Can you email me at jeremy.long@owasp.org?

Jeremy

**Comment by wmaintw** [comment]
Hi Jeremy, sure I will let you know after I publish this gradle plugin

**Comment by wmaintw** [comment]
Hi Sion,

I might know why gradle says "No such property outputDirectory", I believe that you are using version `0.0.4` instead of `0.0.5`, and customize `outputDirectory` feature was implemented in version `0.0.5`.  This is my fault, I implemented this feature and created the pull request, published it to Gradle plugin portal and maven central, but when I update the README.md file, to explain how to customize outputDirecotory property, I forgot to modify the version information in README.md file. 

So would you please try again using version `0.0.5`?

In addition, previously I just reviewed you changes, and today I downloaded the changes and performed a local test, and found that there's an issue, that I can not customize plugin configurations in client project. 

Here's what I did:
- Merge your changes to my local dependency-check-gradle project
- Build this gradle plugin and publish it to local directory
- Client project apply this gradle plugin
- Try to customize the report output directory to "./build/security-report" in client project like this:

``` groovy
allprojects {
    dependencyCheck {
        outputDirectory = "./build/security-report"
    }
}
```
- Run gradle task dependencyCheck and check the report, and found that the security reports still be placed under folder "./reports"

Would you please have a look?

Best Regards.

MA, Wei

**Comment by jeremylong** [comment]
This PR has been merged.

**Comment by willis7** [comment]
@wmaintw, the unit test below shows that when we override the default '.reports', with 'outputDir' the same is seen in the task:

```
def 'tasks use correct values when extension is used'() {
        when:
        project.dependencyCheck {
            proxyServer = '127.0.0.1'
            proxyPort = 3128
            proxyUsername = 'proxyUsername'
            proxyPassword = 'proxyPassword'
            cveUrl12Modified = 'cveUrl12Modified'
            cveUrl20Modified = 'cveUrl20Modified'
            cveStartYear = 2002
            cveUrl12Base = 'cveUrl12Base'
            cveUrl20Base = 'cveUrl20Base'
            outputDirectory = 'outputDirectory'
        }

        then:
        Task task = project.tasks.findByName( 'dependencyCheck' )
        task.proxyServer == '127.0.0.1'
        task.proxyPort == 3128
        task.proxyUsername == 'proxyUsername'
        task.proxyPassword == 'proxyPassword'
        task.cveUrl12Modified == 'cveUrl12Modified'
        task.cveUrl20Modified == 'cveUrl20Modified'
        task.cveStartYear == 2002
        task.cveUrl12Base == 'cveUrl12Base'
        task.cveUrl20Base == 'cveUrl20Base'
        task.outputDirectory == 'outputDirectory'
    }
```

I will write an integration test this evening to see if I can prove the same this evening.

**Comment by willis7** [comment]
I have just coded an integration test and it does indeed fail with the scenario you mentioned.
[failing test added](https://github.com/willis7/DependencyCheck/tree/cafa0d657800d51da0e5f68cfcbd791724b457f4)

I'm a little confused as the unit test would indicate this is working. I suspect I have missed something with the convention mapping. I will work on fixing this.

**Comment by willis7** [comment]
@wmaintw, thanks for spotting this one. Stupid mistake on my behalf. I have fixed the code and the integration test now confirms the fix.

498835015ae5860c21789da169a8dbbf54a38fe7

@jeremylong I will create another pull request.

**Pull request closed without merging**
