### PR TITLE
build: Switch from JMockit to Mockito & build target to Java 11

### LINKED ISSUE #6809: Change mocking framework to be Java 11+ compatible
Uncovered in the attempts to upgrade to Java 11: The JMockit library is not compatible with modern java, causing JaCoCo to run into IndexOutOfBoundExceptions in coverage analysis

See also https://github.com/jacoco/jacoco/issues/896#issuecomment-500944865

Changing `<jacoco-maven-plugin.version>0.8.12</jacoco-maven-plugin.version>` to `<jacoco-maven-plugin.version>0.8.3</jacoco-maven-plugin.version>` resolves 

```
[ERROR] Errors: 
[ERROR] org.owasp.dependencycheck.AnalysisTaskTest.shouldAnalyzeReturnsFalseIfTheFileTypeAnalyzerDoesNotAcceptTheDependency
[ERROR]   Run 1: AnalysisTaskTest.shouldAnalyzeReturnsFalseIfTheFileTypeAnalyzerDoesNotAcceptTheDependency » ArrayIndexOutOfBounds Index 2562 out of bounds for length 777
[ERROR]   Run 2: AnalysisTaskTest.shouldAnalyzeReturnsFalseIfTheFileTypeAnalyzerDoesNotAcceptTheDependency » ArrayIndexOutOfBounds Index 2562 out of bounds for length 777
[INFO] 
[ERROR] org.owasp.dependencycheck.AnalysisTaskTest.shouldAnalyzeReturnsTrueForNonFileTypeAnalyzers
[ERROR]   Run 1: AnalysisTaskTest.shouldAnalyzeReturnsTrueForNonFileTypeAnalyzers » ArrayIndexOutOfBounds Index 2562 out of bounds for length 777
[ERROR]   Run 2: AnalysisTaskTest.shouldAnalyzeReturnsTrueForNonFileTypeAnalyzers » ArrayIndexOutOfBounds Index 2562 out of bounds for length 777
[INFO] 
[ERROR] org.owasp.dependencycheck.AnalysisTaskTest.shouldAnalyzeReturnsTrueIfTheFileTypeAnalyzersAcceptsTheDependency
[ERROR]   Run 1: AnalysisTaskTest.shouldAnalyzeReturnsTrueIfTheFileTypeAnalyzersAcceptsTheDependency » ArrayIndexOutOfBounds Index 2562 out of bounds for length 777
[ERROR]   Run 2: AnalysisTaskTest.shouldAnalyzeReturnsTrueIfTheFileTypeAnalyzersAcceptsTheDependency » ArrayIndexOutOfBounds Index 2562 out of bounds for length 777
[INFO] 
[ERROR] org.owasp.dependencycheck.AnalysisTaskTest.taskAnalyzes
[ERROR]   Run 1: AnalysisTaskTest.taskAnalyzes » ArrayIndexOutOfBounds Index 2562 out of bounds for length 777
[ERROR]   Run 2: AnalysisTaskTest.taskAnalyzes » ArrayIndexOutOfBounds Index 2562 out of bounds for length 777
[INFO] 
[ERROR] org.owasp.dependencycheck.AnalysisTaskTest.taskDoesNothingIfItShouldNotAnalyze
[ERROR]   Run 1: AnalysisTaskTest.taskDoesNothingIfItShouldNotAnalyze » ArrayIndexOutOfBounds Index 2562 out of bounds for length 777
[ERROR]   Run 2: AnalysisTaskTest.taskDoesNothingIfItShouldNotAnalyze » ArrayIndexOutOfBounds Index 2562 out of bounds for length 777
[INFO] 
[ERROR] org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzerTest.testAnalyze
[ERROR]   Run 1: DependencyBundlingAnalyzerTest.testAnalyze » ArrayIndexOutOfBounds Index 3588 out of bounds for length 1169
[ERROR]   Run 2: DependencyBundlingAnalyzerTest.testAnalyze » ArrayIndexOutOfBounds Index 3588 out of bounds for length 1169
[INFO] 
[ERROR] org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzerTest.testFirstPathIsShortest
[ERROR]   Run 1: DependencyBundlingAnalyzerTest.testFirstPathIsShortest » ArrayIndexOutOfBounds Index 3588 out of bounds for length 1169
[ERROR]   Run 2: DependencyBundlingAnalyzerTest.testFirstPathIsShortest » ArrayIndexOutOfBounds Index 3588 out of bounds for length 1169
[INFO] 
[ERROR] org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzerTest.testGetAnalysisPhase
[ERROR]   Run 1: DependencyBundlingAnalyzerTest.testGetAnalysisPhase » ArrayIndexOutOfBounds Index 3588 out of bounds for length 1169
[ERROR]   Run 2: DependencyBundlingAnalyzerTest.testGetAnalysisPhase » ArrayIndexOutOfBounds Index 3588 out of bounds for length 1169
[INFO] 
[ERROR] org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzerTest.testGetName
[ERROR]   Run 1: DependencyBundlingAnalyzerTest.testGetName » ArrayIndexOutOfBounds Index 3588 out of bounds for length 1169
[ERROR]   Run 2: DependencyBundlingAnalyzerTest.testGetName » ArrayIndexOutOfBounds Index 3588 out of bounds for length 1169
[INFO] 
[ERROR] org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzerTest.testIsCore
[ERROR]   Run 1: DependencyBundlingAnalyzerTest.testIsCore » ArrayIndexOutOfBounds Index 3588 out of bounds for length 1169
[ERROR]   Run 2: DependencyBundlingAnalyzerTest.testIsCore » ArrayIndexOutOfBounds Index 3588 out of bounds for length 1169
[INFO] 
[ERROR] org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzerTest.testIsShaded
[ERROR]   Run 1: DependencyBundlingAnalyzerTest.testIsShaded » ArrayIndexOutOfBounds Index 3588 out of bounds for length 1169
[ERROR]   Run 2: DependencyBundlingAnalyzerTest.testIsShaded » ArrayIndexOutOfBounds Index 3588 out of bounds for length 1169
[INFO] 
[ERROR] org.owasp.dependencycheck.analyzer.DependencyBundlingAnalyzerTest.testIsWebJar
[ERROR]   Run 1: DependencyBundlingAnalyzerTest.testIsWebJar » ArrayIndexOutOfBounds Index 3588 out of bounds for length 1169
[ERROR]   Run 2: DependencyBundlingAnalyzerTest.testIsWebJar » ArrayIndexOutOfBounds Index 3588 out of bounds for length 1169
[INFO] 
[ERROR] org.owasp.dependencycheck.data.update.EngineVersionCheckTest.testGetCurrentReleaseVersion
[ERROR]   Run 1: EngineVersionCheckTest.testGetCurrentReleaseVersion » ArrayIndexOutOfBounds Index 3849 out of bounds for length 2392
[ERROR]   Run 2: EngineVersionCheckTest.testGetCurrentReleaseVersion » ArrayIndexOutOfBounds Index 3849 out of bounds for length 2392
[INFO] 
[ERROR] org.owasp.dependencycheck.data.update.EngineVersionCheckTest.testShouldUpdate
[ERROR]   Run 1: EngineVersionCheckTest.testShouldUpdate » ArrayIndexOutOfBounds Index 3849 out of bounds for length 2392
[ERROR]   Run 2: EngineVersionCheckTest.testShouldUpdate » ArrayIndexOutOfBounds Index 3849 out of bounds for length 2392

```

Indicating that the test-failures I see locally are caused by this outdated and apparently unmaintained (see e.g. discussion on https://github.com/jmockit/jmockit1/issues/729) Mock library

### PR DESCRIPTION
**Pull request by aikebah**
## Description of Change

Change mocking in the testcases from JMockit ot Mockito and update the compiler-target to Java 11.
Because of the bump in required Java version also updated the version to the next major as from this change onward Java 11 will be required to run DependencyCheck (some of the mocking required Mockito 5 which also requires Java 11)

One testcase, that was already dynamically disabled on Java 8 has been removed now, as I could not find a way to return it to operational state.

## Have test cases been added to cover the new functionality?

No new functionality, only a replacement of a mocking framework in the test cases and a bump in Java version

### CODE REVIEW

**Comment by aikebah** [comment]
@jeremylong you may want to release a 10.x bugfix with the latest changes since 10.0.3 before integrating as this PR also switches minimum java version used at runtime to Java 11.

**Comment by jeremylong** [comment]
There will be other breaking changes in 11.0 - so yes, I was planning on another release before merging the breaking changes.

**Comment by aikebah** [comment]
> There will be other breaking changes in 11.0 - so yes, I was planning on another release before merging the breaking changes.

Created a new 10.0.4 milestone and re-targeted the already merged PRs to that milestone, so that the 11.0.0 milestone now only has the unmerged, breaking, changes allocated

**Review by jeremylong — APPROVED** [review]
LGTM

**Review by jeremylong — APPROVED** [review]
LGTM

**Pull request merged**
