### PR TITLE
feat: Support Package.swift version 3 Specification

### PR DESCRIPTION
**Pull request by tx2**
## Description of Change

With the recent release of Swift 5.10 there is a new specification for the Package.resolved dependencies file. This PR aims to support the new spec on the analyzer since the structure of the file has changed.

## Have test cases been added to cover the new functionality?

*yes*

### CODE REVIEW

**Review by aikebah — APPROVED** [review]
LGTM

Thanks for the PR

**Comment by aikebah** [comment]
@jeremylong Do you see a need for a 9.1.1 bugfix release? Or should we bump milestone to 9.2.0 and merge this PR for next release?

**Review by jeremylong — APPROVED** [review]
LGTM

**Comment by jeremylong** [comment]
I'm planning on just bumping the entire milestone to 9.2.0 - and just not releasing 9.1.1.

**Pull request merged**
