### PR TITLE
Analyze dependencies from CocoaPods Podfile.lock

### PR DESCRIPTION
**Pull request by Dahlgren**
## Description of Change

Adds analyze of `Podfile.lock` files which are generated based on `Podfile` dependencies. The resulting dependency tree is added as dependencies to the engine.

## Have test cases been added to cover the new functionality?

*yes*

### CODE REVIEW

**Comment by jeremylong** [comment]
Can one of the admins verify this patch?

**Comment by jorenvh1** [comment]
Can this be merged?

**Comment by jeremylong** [comment]
@jorenvh1 yes - I'll be merging this shortly.  I was in the middle of some other updates - but this will be included in the next release.

**Comment by anoop4real** [comment]
Can you provide the exact command ?  Should I "scan " to podfile.lock?

**Comment by tdwyer** [comment]
This command works
```
bin/dependency-check.sh --enableExperimental --project TheProjectName --out output --scan /home/user/ios_security/ios
```

**Pull request merged**
