### PR TITLE
Implement analyzer for go modules (>=1.11)

### PR DESCRIPTION
**Pull request by mvdbos**
## Fixes Issue #
Lack of support for Go modules. 

## Description of Change
This implementation supports the native `go mod` way of working with dependencies, which is enabled since go 1.11 and will be the default as of go 1.13.

## Have test cases been added to cover the new functionality?
Yes

### CODE REVIEW

**Comment by mvdbos** [comment]
Related to #1560.

**Comment by mvdbos** [comment]
@jeremylong

**Comment by kimahcm** [comment]
Hi! @mvdbos @jeremylong I was wondering, is this PR going to be merged soon?

**Comment by mvdbos** [comment]
> Hi! @mvdbos @jeremylong I was wondering, is this PR going to be merged soon?

@jeremylong When do you think you might have some time to look at it? If there is anything I can help with, or need to change, please let me know.

**Comment by jeremylong** [comment]
Yes - this PR will get merged before the next release (which should happen before June 29th).  I have already done some initial review and I have a few minor updates to make that will help with the analysis.

**Comment by jeremylong** [comment]
@mvdbos due to an issue with a .DS_Store being checked into this PR - I ended up creating a new PR (see #2018).

**Pull request closed without merging**
