### PR TITLE
Minor code tweaks.

### PR DESCRIPTION
**Pull request by awhitford**
- Removed unnecessary imports.
- Collapsed nested if statements.
- Removed unnecessary parentheses.
- Added final keyword.

### CODE REVIEW

**Comment by nkrishnawat** [comment]
You look happy but your dog looks angry at me..

**Comment by awhitford** [comment]
My dog's tail is wagging; he isn't angry.

**Comment by nkrishnawat** [comment]
Cool, 

what_bf4bc3_1374948

Happy Diwali..

( This post is too much for GitHub, I will remove this in couple of days)

**Comment by nkrishnawat** [comment]
Any big change in @WAM, new hires or some left I know of ?

**Pull request merged**
